#!/bin/sh

SESSION1='rtvision-app'
BASE_REPO_DIR=~/monorepo
OPEN_SOURCE_DIR=~/open-source

# set up tmux
tmux start-server

# create a new tmux sessiona and -x and -y come from https://unix.stackexchange.com/questions/569729/tmux-not-splitting-panes-with-desired-percentage-size
tmux new-session -d -s $SESSION1 -c $BASE_REPO_DIR/ -n 'ui' -x "$(tput cols)" -y "$(tput lines)"
tmux split-window -h -l 75% -c $BASE_REPO_DIR
tmux select-pane -t ui.left
tmux split-window -v -l 40% -c $BASE_REPO_DIR
tmux select-pane -t ui.right

tmux new-window -t $SESSION1:2 -n 'docker' -c $BASE_REPO_DIR
tmux new-window -t $SESSION1:3 -n 'notes' -c '~'

tmux new-window -t $SESSION1:4 -n 'add-in' -c $BASE_REPO_DIR/apps/add-in-word-excel
tmux split-window -h -l 75% -t add-in -c $BASE_REPO_DIR/apps/add-in-word-excel
tmux select-pane -t add-in.right

tmux new-window -t $SESSION1:5 -n 'aws-infrastructure' -c $BASE_REPO_DIR
tmux new-window -t $SESSION1:6 -n 'db' -c $BASE_REPO_DIR

tmux new-window -t $SESSION1:7 -n 'open-source' -c $OPEN_SOURCE_DIR
tmux split-window -h -l 70% -t open-source -c $OPEN_SOURCE_DIR
tmux split-window -v -l 5% -t open-source.left -c $OPEN_SOURCE_DIR
tmux select-pane -t open-source.right

# Need to sleep to make sure shells are active
sleep 1
tmux send-keys -t ui.top-left 'pnpm dev --filter=@rtvision/app-ui'
tmux send-keys -t ui.bottom-left 'pnpm dev --filter=@rtvision/app-ui^...'
tmux send-keys -t docker 'make' Enter
tmux send-keys -t add-in.left 'pnpm start' Enter
tmux send-keys -t aws-infrastructure "ssh bastion -t 'cd aws-infrastructure; bash --login'" Enter
tmux send-keys -t db 'sleep 11' Enter 'psql -U postgres -h localhost rtvision' Enter
tmux send-keys -t open-source.bottom-left 'ssh -L 3333:github.com:22 ssh -N' # Do not hit enter for this just want it there when I need to push/pull to/from github

# go to 3rd window so it is marked as the previous window and accessed via the back key
tmux select-window -t $SESSION1:docker
tmux select-window -t $SESSION1:ui

tmux attach-session -t $SESSION1
